"""empty message

Revision ID: 4aa3a43f85d7
Revises: 
Create Date: 2019-06-15 22:24:48.908285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa3a43f85d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('usuario', sa.String(length=60), nullable=True),
    sa.Column('primeiro_nome', sa.String(length=60), nullable=True),
    sa.Column('ultimo_nome', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funcionarios_email'), 'funcionarios', ['email'], unique=True)
    op.create_index(op.f('ix_funcionarios_primeiro_nome'), 'funcionarios', ['primeiro_nome'], unique=False)
    op.create_index(op.f('ix_funcionarios_ultimo_nome'), 'funcionarios', ['ultimo_nome'], unique=False)
    op.create_index(op.f('ix_funcionarios_usuario'), 'funcionarios', ['usuario'], unique=True)
    op.create_table('noticias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=60), nullable=True),
    sa.Column('caminho_imagem', sa.String(length=100), nullable=True),
    sa.Column('texto', sa.String(length=3000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noticias')
    op.drop_index(op.f('ix_funcionarios_usuario'), table_name='funcionarios')
    op.drop_index(op.f('ix_funcionarios_ultimo_nome'), table_name='funcionarios')
    op.drop_index(op.f('ix_funcionarios_primeiro_nome'), table_name='funcionarios')
    op.drop_index(op.f('ix_funcionarios_email'), table_name='funcionarios')
    op.drop_table('funcionarios')
    # ### end Alembic commands ###
